---
title: "Untitled"
output: html_document
---
#6.5
```{r}
good <- function(C,xbar,S,n,q,alpha){
 transform <- C %*% xbar
C %*% S %*% t(C)
T_square <- n * ( t(C%*%xbar) %*% solve(C%*%S%*%t(C)) %*% C%*%xbar  )
F_value <- (n-1)*(q-1)/(n-q+1) * qf(1-alpha, df1 = q-1, df2 = n-q+1)
listOfvalue <- list(T_square,F_value,transform)



return(listOfvalue)
}


n <- 40
q <- 3
alpha <- 0.05
xbar <- matrix(c(46.1,57.3,50.4), ncol = 1, nrow =3, byrow = TRUE)
S <- matrix(c(101.3,63.0,71.0,63.0,80.2,55.6,71.0,55.6,97.4), nrow = 3,ncol = 3, byrow = TRUE)
C <- matrix(c(1,-1,0,0,1,-1), ncol = 3, nrow = 2, byrow = TRUE)


good(C,xbar,S,40,3,0.05)

-11.2 - sqrt(6.660417)*sqrt(((head(C,1))%*%S%*%t(head(C,1)))/n)
-11.2 + sqrt(6.660417)*sqrt(((head(C,1))%*%S%*%t(head(C,1)))/n)
6.9 - sqrt(6.660417)*sqrt(((C[2,] )%*%S%*%matrix(C[2,]))/n)
6.9 + sqrt(6.660417)*sqrt(((C[2,] )%*%S%*%matrix(C[2,]))/n)





```

#6.6
```{r}

(xbar_1 <- matrix(c(mean(3,1,2),mean(3,6,3)),ncol = 1,nrow = 2, byrow = TRUE))
(xbar_2 <- matrix(c(mean(2,5,3,2),mean(3,1,1,3)),ncol = 1,nrow = 2, byrow = TRUE))

(S_1 <- cov(matrix(c(3,1,2,3,6,3) , ncol = 2,nrow = 3, byrow = FALSE)))
(S_2 <- cov(matrix(c(2,5,3,2,3,1,1,3),ncol = 2,nrow = 4, byrow = FALSE)))

#(a)
(S_pooled <- 2/5*S_1 + 2/5*S_2)


#(B)
population1 = matrix(c(9,6,9,3,2,7), nrow = 3, ncol = 2, byrow = FALSE)
population2 = matrix(c(0,2,4,0), nrow = 2, ncol = 2, byrow = FALSE)
population3 = matrix(c(3,1,2,8,9,7), nrow = 3, ncol = 2, byrow = FALSE)


```



#6.13
```{r}
#(a) first variable
a <- c(6,4,8,2,
       3,-3,4,-4,
       -3,-4,3,-4)
nr <- 3
nc <- 4
a_matrix <- matrix(a, nrow = nr, ncol = nc, byrow = TRUE)
funcs <- function(x_bar,xlevelOffactor1_bar, ylevelOffactor2_bar, xyobservation ) {
  first_term <- x_bar
  second_term <- xlevelOffactor1_bar - x_bar
  third_term <- ylevelOffactor2_bar - x_bar
  fourth_term <- xyobservation - xlevelOffactor1_bar - ylevelOffactor2_bar + x_bar
  return(c(first_term,
              second_term,
              third_term,
              fourth_term))
}
af_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
as_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
at_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
afo_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
  
for (i in 1:nr){
  for(j in 1:nc) {
    print(paste(i,j,sep=","))
    out <- funcs(mean(a),mean(a_matrix[i,]),mean(a_matrix[,j]),a_matrix[i,j])
    print(out)
    print("-----------------------------")
    af_matrix[i,j] <- out[1]
    as_matrix[i,j] <- out[2]
    at_matrix[i,j] <- out[3]
    afo_matrix[i,j] <- out[4]
    
  }
}
af_matrix
as_matrix
at_matrix
afo_matrix
#(a) second variable
b <- c(8,6,12,6,
       8,2,3,3,
       2,-5,-3,-6)
nr <- 3
nc <- 4
a_matrix <- matrix(b, nrow = nr, ncol = nc, byrow = TRUE)
funcs <- function(x_bar,xlevelOffactor1_bar, ylevelOffactor2_bar, xyobservation ) {
  first_term <- x_bar
  second_term <- xlevelOffactor1_bar - x_bar
  third_term <- ylevelOffactor2_bar - x_bar
  fourth_term <- xyobservation - xlevelOffactor1_bar - ylevelOffactor2_bar + x_bar
  return(c(first_term,
              second_term,
              third_term,
              fourth_term))
}
bf_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
bs_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
bt_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
bfo_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
  
for (i in 1:nr){
  for(j in 1:nc) {
    print(paste(i,j,sep=","))
    out <- funcs(mean(b),mean(a_matrix[i,]),mean(a_matrix[,j]),a_matrix[i,j])
    print(out)
    print("-----------------------------")
    bf_matrix[i,j] <- out[1]
    bs_matrix[i,j] <- out[2]
    bt_matrix[i,j] <- out[3]
    bfo_matrix[i,j] <- out[4]
    
  }
}
bf_matrix
bs_matrix
bt_matrix
bfo_matrix
#-----------------------------------------------------------------------------
#(b)
b %*% b
a %*% a

#-----------------------
#first variable
as.vector(af_matrix) %*% as.vector(af_matrix)
as.vector(as_matrix) %*% as.vector(as_matrix)
as.vector(at_matrix) %*% as.vector(at_matrix)
as.vector(afo_matrix) %*% as.vector(afo_matrix)
#second variable
as.vector(bf_matrix) %*% as.vector(bf_matrix)
as.vector(bs_matrix) %*% as.vector(bs_matrix)
as.vector(bt_matrix) %*% as.vector(bt_matrix)
as.vector(bfo_matrix) %*% as.vector(bfo_matrix)

SCP_mean <- as.vector(af_matrix) %*% as.vector(bf_matrix) 
SCP_fac1 <- as.vector(as_matrix) %*% as.vector(bs_matrix)
SCP_fac2 <- as.vector(at_matrix) %*% as.vector(bt_matrix)
SCP_resi <- as.vector(afo_matrix) %*% as.vector(bfo_matrix)
a %*% b

SSP_fac1 <- matrix(c(as.vector(as_matrix) %*% as.vector(as_matrix),
                     SCP_fac1,
                     SCP_fac1,
                     as.vector(bs_matrix) %*% as.vector(bs_matrix)), nrow = 2, ncol = 2, byrow = TRUE)
SSP_fac2 <- matrix(c(as.vector(at_matrix) %*% as.vector(at_matrix),
                     SCP_fac2,
                     SCP_fac2,
                     as.vector(bt_matrix) %*% as.vector(bt_matrix)), nrow = 2, ncol = 2, byrow = TRUE)
SSP_resid <- matrix(c(as.vector(afo_matrix) %*% as.vector(afo_matrix),
                      SCP_resi,
                      SCP_resi,
                      as.vector(bfo_matrix) %*% as.vector(bfo_matrix)), nrow = 2, ncol = 2, byrow = TRUE)
SSP_cor <- matrix(c(a %*% a - as.vector(af_matrix) %*% as.vector(af_matrix),
                    SCP_fac1+SCP_fac2+SCP_resi,
                    SCP_fac1+SCP_fac2+SCP_resi,
                    b %*% b - as.vector(bf_matrix) %*% as.vector(bf_matrix)), nrow = 2, ncol = 2, byrow = TRUE)



lambda1 <- det(SSP_resid)/(det(SSP_fac1)+det(SSP_resid))
lambda2 <- det(SSP_resid)/(det(SSP_fac2)+det(SSP_resid))
p <- 2
-((6)-((p+1-nr+1)/2))*log(lambda1) > qchisq(0.95, df=(nr-1)*p)
-((6)-((p+1-nc+1)/2))*log(lambda2) > qchisq(0.95, df=(nc-1)*p)

f+s+t+fo
#   df
f # 3*4 - 1
s # 3-1
t # 4-1
fo #(3-1)*(4-1)
```

#6.14
```{r}
#(a) first variable
c <- c(14,6,8,16,
       1,5,0,2,
       3,-2,-11,-6)
nr <- 3
nc <- 4
a_matrix <- matrix(c, nrow = nr, ncol = nc, byrow = TRUE)
funcs <- function(x_bar,xlevelOffactor1_bar, ylevelOffactor2_bar, xyobservation ) {
  first_term <- x_bar
  second_term <- xlevelOffactor1_bar - x_bar
  third_term <- ylevelOffactor2_bar - x_bar
  fourth_term <- xyobservation - xlevelOffactor1_bar - ylevelOffactor2_bar + x_bar
  return(c(first_term,
              second_term,
              third_term,
              fourth_term))
}
cf_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
cs_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
ct_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
cfo_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
  
for (i in 1:nr){
  for(j in 1:nc) {
    print(paste(i,j,sep=","))
    out <- funcs(mean(c),mean(a_matrix[i,]),mean(a_matrix[,j]),a_matrix[i,j])
    print(out)
    print("-----------------------------")
    cf_matrix[i,j] <- out[1]
    cs_matrix[i,j] <- out[2]
    ct_matrix[i,j] <- out[3]
    cfo_matrix[i,j] <- out[4]
    
  }
}
cf_matrix
cs_matrix
ct_matrix
cfo_matrix
c %*% c
as.vector(cf_matrix) %*% as.vector(cf_matrix)
as.vector(cs_matrix) %*% as.vector(cs_matrix)
as.vector(ct_matrix) %*% as.vector(ct_matrix)
as.vector(cfo_matrix) %*% as.vector(cfo_matrix)


#(a) second variable
d <- c(8,2,2,-4,
       6,12,15,7,
       -2,7,1,6)
nr <- 3
nc <- 4
a_matrix <- matrix(d, nrow = nr, ncol = nc, byrow = TRUE)
funcs <- function(x_bar,xlevelOffactor1_bar, ylevelOffactor2_bar, xyobservation ) {
  first_term <- x_bar
  second_term <- xlevelOffactor1_bar - x_bar
  third_term <- ylevelOffactor2_bar - x_bar
  fourth_term <- xyobservation - xlevelOffactor1_bar - ylevelOffactor2_bar + x_bar
  return(c(first_term,
              second_term,
              third_term,
              fourth_term))
}
df_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
ds_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
dt_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
dfo_matrix <- matrix(double(nr*nc), nrow = nr, ncol = nc, byrow = TRUE)
  
for (i in 1:nr){
  for(j in 1:nc) {
    print(paste(i,j,sep=","))
    out <- funcs(mean(d),mean(a_matrix[i,]),mean(a_matrix[,j]),a_matrix[i,j])
    print(out)
    print("-----------------------------")
    df_matrix[i,j] <- out[1]
    ds_matrix[i,j] <- out[2]
    dt_matrix[i,j] <- out[3]
    dfo_matrix[i,j] <- out[4]
    
  }
}
df_matrix
ds_matrix
dt_matrix
dfo_matrix

a12 <- matrix(c(4,5,8,-3), nrow = 4, ncol = 1, byrow = TRUE)
b12 <- matrix(c(-1,1,-1,5), nrow = 4, ncol = 1, byrow = TRUE)
c12 <- matrix(c(-3,-6,-7,-2), nrow = 4, ncol = 1, byrow = TRUE)
asd <- 4*(a12 %*% t(a12) + b12 %*% t(b12) + c12 %*% t(c12))



a1 <- matrix(c(1,3,3,-1), nrow = 4, ncol = 1, byrow = TRUE)
b1 <- matrix(c(-2,-2,0,2), nrow = 4, ncol = 1, byrow = TRUE)
c1 <- matrix(c(4,1,-4,1), nrow = 4, ncol = 1, byrow = TRUE)
d1 <- matrix(c(-3,-2,1,-2), nrow = 4, ncol = 1, byrow = TRUE)
asdf <- 3*(a1 %*% t(a1) + b1 %*% t(b1) + c1 %*% t(c1) + d1 %*% t(d1))


a <- matrix(c(0,-3,0,7), nrow = 4, ncol = 1, byrow = TRUE)
b <- matrix(c(1,0,-5,-2), nrow = 4, ncol = 1, byrow = TRUE)
c <- matrix(c(-1,3,1,-1), nrow = 4, ncol = 1, byrow = TRUE)
d <- matrix(c(0,0,4,-4), nrow = 4, ncol = 1, byrow = TRUE)
e <- matrix(c(2,1,-4,-3), nrow = 4, ncol = 1, byrow = TRUE)
f <- matrix(c(-1,0,3,0), nrow = 4, ncol = 1, byrow = TRUE)
g <- matrix(c(0,-2,2,4), nrow = 4, ncol = 1, byrow = TRUE)
h <- matrix(c(-1,1,-1,-1), nrow = 4, ncol = 1, byrow = TRUE)
i <- matrix(c(-2,2,4,-4), nrow = 4, ncol = 1, byrow = TRUE)
j <- matrix(c(0,0,2,2), nrow = 4, ncol = 1, byrow = TRUE)
k <- matrix(c(1,-1,-3,-3), nrow = 4, ncol = 1, byrow = TRUE)
l <- matrix(c(1,-1,-3,5), nrow = 4, ncol = 1, byrow = TRUE)

asdfg <- a %*% t(a) +
  b %*% t(b) +
  c %*% t(c) +
  d %*% t(d) +
  e %*% t(e) +
  f %*% t(f) +
  g %*% t(g) + 
  h %*% t(h) + 
  i %*% t(i) + 
  j %*% t(j) + 
  k %*% t(k) + 
  l %*% t(l)




corr <- asd+asdf+asdfg

lamb <- det(asdfg)/(det(asdf)+det(asdfg))

-((6)-((5-4+1)/2))*log(lamb) > qchisq(0.95, df = 4*(3))


alpha = .95
g = 3
b = 4
n = 
p = 4  
E = 
(e - m) - qt(alpha/(p*g(g-1)),(g-1)(b-1))*sqrt((E/((g-1)*(b-1)))*(1/(b*n)))
(e - m) + qt(alpha/(p*g(g-1)),(g-1)(b-1))*sqrt((E/((g-1)*(b-1)))*(1/(b*n)))


```
